<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `Phones`
//

// `Phone_Carriers`
$Phone_Carriers = array(
  array('idPhone_Carriers' => '1','idPhone_Countries' => '2','key_name' => 'airfire_mobile','carrier_name' => 'Airfire Mobile','sms' => '{number}@sms.airfiremobile.com'),
  array('idPhone_Carriers' => '2','idPhone_Countries' => '2','key_name' => 'alltel','carrier_name' => 'Alltel','sms' => '{number}@message.alltel.com'),
  array('idPhone_Carriers' => '3','idPhone_Countries' => '2','key_name' => 'alltel_allied','carrier_name' => 'Alltel (Allied Wireless)','sms' => '{number}@sms.alltelwireless.com'),
  array('idPhone_Carriers' => '4','idPhone_Countries' => '2','key_name' => 'alaska_communications','carrier_name' => 'Alaska Communications','sms' => '{number}@msg.acsalaska.com'),
  array('idPhone_Carriers' => '5','idPhone_Countries' => '2','key_name' => 'ameritech','carrier_name' => 'Ameritech','sms' => '{number}@paging.acswireless.com'),
  array('idPhone_Carriers' => '6','idPhone_Countries' => '2','key_name' => 'assurance_wireless','carrier_name' => 'Assurance Wireless','sms' => '{number}@vmobl.com'),
  array('idPhone_Carriers' => '7','idPhone_Countries' => '2','key_name' => 'at_and_t','carrier_name' => 'AT&T Wireless','sms' => '{number}@txt.att.net'),
  array('idPhone_Carriers' => '8','idPhone_Countries' => '2','key_name' => 'at_and_t_mobility','carrier_name' => 'AT&T Mobility (Cingular)','sms' => '{number}@txt.att.net'),
  array('idPhone_Carriers' => '9','idPhone_Countries' => '2','key_name' => 'at_and_t_paging','carrier_name' => 'AT&T Enterprise Paging','sms' => '{number}@page.att.net'),
  array('idPhone_Carriers' => '10','idPhone_Countries' => '2','key_name' => 'at_and_t_global_sms','carrier_name' => 'AT&T Global Smart Messaging Suite','sms' => '{number}@sms.smartmessagingsuite.com'),
  array('idPhone_Carriers' => '11','idPhone_Countries' => '2','key_name' => 'bellsouth','carrier_name' => 'BellSouth','sms' => '{number}@bellsouth.cl'),
  array('idPhone_Carriers' => '12','idPhone_Countries' => '2','key_name' => 'bluegrass','carrier_name' => 'Bluegrass Cellular','sms' => '{number}@sms.bluecell.com'),
  array('idPhone_Carriers' => '13','idPhone_Countries' => '2','key_name' => 'bluesky','carrier_name' => 'Bluesky Communications','sms' => '{number}@psms.bluesky.as'),
  array('idPhone_Carriers' => '14','idPhone_Countries' => '2','key_name' => 'blueskyfrog','carrier_name' => 'BlueSkyFrog','sms' => '{number}@blueskyfrog.com'),
  array('idPhone_Carriers' => '15','idPhone_Countries' => '2','key_name' => 'boostmobile','carrier_name' => 'Boost Mobile','sms' => '{number}@sms.myboostmobile.com'),
  array('idPhone_Carriers' => '16','idPhone_Countries' => '2','key_name' => 'cellcom','carrier_name' => 'Cellcom','sms' => '{number}@cellcom.quiktxt.com'),
  array('idPhone_Carriers' => '17','idPhone_Countries' => '2','key_name' => 'cellularsouth','carrier_name' => 'Cellular South','sms' => '{number}@csouth1.com'),
  array('idPhone_Carriers' => '18','idPhone_Countries' => '2','key_name' => 'centennial_wireless','carrier_name' => 'Centennial Wireless','sms' => '{number}@cwemail.com'),
  array('idPhone_Carriers' => '19','idPhone_Countries' => '2','key_name' => 'chariton_valley','carrier_name' => 'Chariton Valley Wireless','sms' => '{number}@sms.cvalley.net'),
  array('idPhone_Carriers' => '20','idPhone_Countries' => '2','key_name' => 'chat_mobility','carrier_name' => 'Chat Mobility','sms' => '{number}@mail.msgsender.com'),
  array('idPhone_Carriers' => '21','idPhone_Countries' => '2','key_name' => 'cincinnati_bell','carrier_name' => 'Cincinnati Bell','sms' => '{number}@gocbw.com'),
  array('idPhone_Carriers' => '22','idPhone_Countries' => '2','key_name' => 'cingular','carrier_name' => 'Cingular (Postpaid)','sms' => '{number}@cingular.com'),
  array('idPhone_Carriers' => '23','idPhone_Countries' => '2','key_name' => 'cleartalk','carrier_name' => 'Cleartalk Wireless','sms' => '{number}@sms.cleartalk.us'),
  array('idPhone_Carriers' => '24','idPhone_Countries' => '2','key_name' => 'comcast_pcs','carrier_name' => 'Comcast PCS','sms' => '{number}@comcastpcs.textmsg.com'),
  array('idPhone_Carriers' => '25','idPhone_Countries' => '2','key_name' => 'cricket','carrier_name' => 'Cricket','sms' => '{number}@sms.mycricket.com'),
  array('idPhone_Carriers' => '26','idPhone_Countries' => '2','key_name' => 'cspire','carrier_name' => 'C Spire Wireless','sms' => '{number}@cspire1.com'),
  array('idPhone_Carriers' => '27','idPhone_Countries' => '2','key_name' => 'dtc_wireless','carrier_name' => 'DTC Wireless','sms' => '{number}@sms.advantagecell.net'),
  array('idPhone_Carriers' => '28','idPhone_Countries' => '2','key_name' => 'element','carrier_name' => 'Element Mobile','sms' => '{number}@sms.elementmobile.net'),
  array('idPhone_Carriers' => '29','idPhone_Countries' => '2','key_name' => 'esendex','carrier_name' => 'Esendex','sms' => '{number}@echoemail.net'),
  array('idPhone_Carriers' => '30','idPhone_Countries' => '2','key_name' => 'general_comm','carrier_name' => 'General Communications Inc.','sms' => '{number}@mobile.gci.net'),
  array('idPhone_Carriers' => '31','idPhone_Countries' => '2','key_name' => 'golden_state','carrier_name' => 'Golden State Cellular','sms' => '{number}@gscsms.com'),
  array('idPhone_Carriers' => '32','idPhone_Countries' => '2','key_name' => 'google_voice','carrier_name' => 'Google Voice','sms' => '{number}@txt.voice.google.com'),
  array('idPhone_Carriers' => '33','idPhone_Countries' => '2','key_name' => 'greatcall','carrier_name' => 'GreatCall','sms' => '{number}@vtext.com'),
  array('idPhone_Carriers' => '34','idPhone_Countries' => '2','key_name' => 'helio','carrier_name' => 'Helio','sms' => '{number}@myhelio.com'),
  array('idPhone_Carriers' => '35','idPhone_Countries' => '2','key_name' => 'iwireless_tmobile','carrier_name' => 'i wireless (T-Mobile)','sms' => '{number}.iws@iwspcs.net'),
  array('idPhone_Carriers' => '36','idPhone_Countries' => '2','key_name' => 'iwireless_sprint','carrier_name' => 'i wireless (Sprint PCS)','sms' => '{number}@iwirelesshometext.com'),
  array('idPhone_Carriers' => '37','idPhone_Countries' => '2','key_name' => 'kajeet','carrier_name' => 'Kajeet','sms' => '{number}@mobile.kajeet.net'),
  array('idPhone_Carriers' => '38','idPhone_Countries' => '2','key_name' => 'longlines','carrier_name' => 'LongLines','sms' => '{number}@text.longlines.com'),
  array('idPhone_Carriers' => '39','idPhone_Countries' => '2','key_name' => 'metro_pcs','carrier_name' => 'Metro PCS','sms' => '{number}@mymetropcs.com'),
  array('idPhone_Carriers' => '40','idPhone_Countries' => '2','key_name' => 'nextech','carrier_name' => 'Nextech','sms' => '{number}@sms.nextechwireless.com'),
  array('idPhone_Carriers' => '41','idPhone_Countries' => '2','key_name' => 'nextel','carrier_name' => 'Nextel Direct Connect (Sprint)','sms' => '{number}@messaging.nextel.com'),
  array('idPhone_Carriers' => '42','idPhone_Countries' => '2','key_name' => 'pageplus','carrier_name' => 'Page Plus Cellular','sms' => '{number}@vtext.com'),
  array('idPhone_Carriers' => '43','idPhone_Countries' => '2','key_name' => 'pioneer','carrier_name' => 'Pioneer Cellular','sms' => '{number}@zsend.com'),
  array('idPhone_Carriers' => '44','idPhone_Countries' => '2','key_name' => 'psc_wireless','carrier_name' => 'PSC Wireless','sms' => '{number}@sms.pscel.com'),
  array('idPhone_Carriers' => '45','idPhone_Countries' => '2','key_name' => 'rogers_wireless','carrier_name' => 'Rogers Wireless','sms' => '{number}@sms.rogers.com'),
  array('idPhone_Carriers' => '46','idPhone_Countries' => '2','key_name' => 'qwest','carrier_name' => 'Qwest','sms' => '{number}@qwestmp.com'),
  array('idPhone_Carriers' => '47','idPhone_Countries' => '2','key_name' => 'simple_mobile','carrier_name' => 'Simple Mobile','sms' => '{number}@smtext.com'),
  array('idPhone_Carriers' => '48','idPhone_Countries' => '2','key_name' => 'solavei','carrier_name' => 'Solavei','sms' => '{number}@tmomail.net'),
  array('idPhone_Carriers' => '49','idPhone_Countries' => '2','key_name' => 'south_central','carrier_name' => 'South Central Communications','sms' => '{number}@rinasms.com'),
  array('idPhone_Carriers' => '50','idPhone_Countries' => '2','key_name' => 'southernlink','carrier_name' => 'Southern Link','sms' => '{number}@page.southernlinc.com'),
  array('idPhone_Carriers' => '51','idPhone_Countries' => '2','key_name' => 'sprint','carrier_name' => 'Sprint PCS (CDMA)','sms' => '{number}@messaging.sprintpcs.com'),
  array('idPhone_Carriers' => '52','idPhone_Countries' => '2','key_name' => 'straight_talk','carrier_name' => 'Straight Talk','sms' => '{number}@vtext.com'),
  array('idPhone_Carriers' => '53','idPhone_Countries' => '2','key_name' => 'syringa','carrier_name' => 'Syringa Wireless','sms' => '{number}@rinasms.com'),
  array('idPhone_Carriers' => '54','idPhone_Countries' => '2','key_name' => 't_mobile','carrier_name' => 'T-Mobile','sms' => '{number}@tmomail.net'),
  array('idPhone_Carriers' => '55','idPhone_Countries' => '2','key_name' => 'teleflip','carrier_name' => 'Teleflip','sms' => '{number}@teleflip.com'),
  array('idPhone_Carriers' => '56','idPhone_Countries' => '2','key_name' => 'ting','carrier_name' => 'Ting','sms' => '{number}@message.ting.com'),
  array('idPhone_Carriers' => '57','idPhone_Countries' => '2','key_name' => 'tracfone','carrier_name' => 'Tracfone','sms' => '{number}@mmst5.tracfone.com'),
  array('idPhone_Carriers' => '58','idPhone_Countries' => '2','key_name' => 'telus_mobility','carrier_name' => 'Telus Mobility','sms' => '{number}@msg.telus.com'),
  array('idPhone_Carriers' => '59','idPhone_Countries' => '2','key_name' => 'unicel','carrier_name' => 'Unicel','sms' => '{number}@utext.com'),
  array('idPhone_Carriers' => '60','idPhone_Countries' => '2','key_name' => 'us_cellular','carrier_name' => 'US Cellular','sms' => '{number}@email.uscc.net'),
  array('idPhone_Carriers' => '61','idPhone_Countries' => '2','key_name' => 'usa_mobility','carrier_name' => 'USA Mobility','sms' => '{number}@usamobility.net'),
  array('idPhone_Carriers' => '62','idPhone_Countries' => '2','key_name' => 'verizon_wireless','carrier_name' => 'Verizon Wireless','sms' => '{number}@vtext.com'),
  array('idPhone_Carriers' => '63','idPhone_Countries' => '2','key_name' => 'viaero','carrier_name' => 'Viaero','sms' => '{number}@viaerosms.com'),
  array('idPhone_Carriers' => '64','idPhone_Countries' => '2','key_name' => 'virgin_mobile','carrier_name' => 'Virgin Mobile','sms' => '{number}@vmobl.com'),
  array('idPhone_Carriers' => '65','idPhone_Countries' => '2','key_name' => 'voyager_mobile','carrier_name' => 'Voyager Mobile','sms' => '{number}@text.voyagermobile.com'),
  array('idPhone_Carriers' => '66','idPhone_Countries' => '2','key_name' => 'west_central','carrier_name' => 'West Central Wireless','sms' => '{number}@sms.wcc.net'),
  array('idPhone_Carriers' => '67','idPhone_Countries' => '2','key_name' => 'xit_comm','carrier_name' => 'XIT Communications','sms' => '{number}@sms.xit.net'),
  array('idPhone_Carriers' => '68','idPhone_Countries' => '3','key_name' => 'aliant','carrier_name' => 'Aliant','sms' => '{number}@chat.wirefree.ca'),
  array('idPhone_Carriers' => '69','idPhone_Countries' => '3','key_name' => 'bellmobility','carrier_name' => 'Bell Mobility & Solo Mobile','sms' => '{number}@txt.bell.ca'),
  array('idPhone_Carriers' => '70','idPhone_Countries' => '3','key_name' => 'fido','carrier_name' => 'Fido','sms' => '{number}@sms.fido.ca'),
  array('idPhone_Carriers' => '71','idPhone_Countries' => '3','key_name' => 'koodo','carrier_name' => 'Koodo Mobile','sms' => '{number}@msg.telus.com'),
  array('idPhone_Carriers' => '72','idPhone_Countries' => '3','key_name' => 'lynx_mobility','carrier_name' => 'Lynx Mobility','sms' => '{number}@sms.lynxmobility.com'),
  array('idPhone_Carriers' => '73','idPhone_Countries' => '3','key_name' => 'manitoba_telecom','carrier_name' => 'Manitoba Telecom/MTS Mobility','sms' => '{number}@text.mtsmobility.com'),
  array('idPhone_Carriers' => '74','idPhone_Countries' => '3','key_name' => 'northerntel','carrier_name' => 'NorthernTel','sms' => '{number}@txt.northerntelmobility.com'),
  array('idPhone_Carriers' => '75','idPhone_Countries' => '3','key_name' => 'pc_telecom','carrier_name' => 'PC Telecom','sms' => '{number}@mobiletxt.ca'),
  array('idPhone_Carriers' => '76','idPhone_Countries' => '3','key_name' => 'rogers_wireless','carrier_name' => 'Rogers Wireless','sms' => '{number}@sms.rogers.com'),
  array('idPhone_Carriers' => '77','idPhone_Countries' => '3','key_name' => 'sasktel','carrier_name' => 'SaskTel','sms' => '{number}@sms.sasktel.com'),
  array('idPhone_Carriers' => '78','idPhone_Countries' => '3','key_name' => 'telebec','carrier_name' => 'Telebec','sms' => '{number}@txt.telebecmobilite.com'),
  array('idPhone_Carriers' => '79','idPhone_Countries' => '3','key_name' => 'telus','carrier_name' => 'Telus Mobility','sms' => '{number}@msg.telus.com'),
  array('idPhone_Carriers' => '80','idPhone_Countries' => '3','key_name' => 'virgin','carrier_name' => 'Virgin Mobile','sms' => '{number}@vmobile.ca'),
  array('idPhone_Carriers' => '81','idPhone_Countries' => '3','key_name' => 'wind_mobile','carrier_name' => 'Wind Mobile','sms' => '{number}@txt.windmobile.ca'),
  array('idPhone_Carriers' => '82','idPhone_Countries' => '4','key_name' => 'claro','carrier_name' => 'CTI Movil (Claro)','sms' => '{number}@sms.ctimovil.com.ar'),
  array('idPhone_Carriers' => '83','idPhone_Countries' => '4','key_name' => 'movistar','carrier_name' => 'Movistar','sms' => '{number}@sms.movistar.net.ar'),
  array('idPhone_Carriers' => '84','idPhone_Countries' => '4','key_name' => 'nextel','carrier_name' => 'Nextel','sms' => 'TwoWay.{number}@nextel.net.ar'),
  array('idPhone_Carriers' => '85','idPhone_Countries' => '4','key_name' => 'telecom_personal','carrier_name' => 'Telecom (Personal)','sms' => '{number}@alertas.personal.com.ar'),
  array('idPhone_Carriers' => '86','idPhone_Countries' => '5','key_name' => 'setar','carrier_name' => 'Setar Mobile','sms' => '{number}@mas.aw'),
  array('idPhone_Carriers' => '87','idPhone_Countries' => '6','key_name' => 't_mobile','carrier_name' => 'T-Mobile (Optus Zoo)','sms' => '{number}@optusmobile.com.au'),
  array('idPhone_Carriers' => '88','idPhone_Countries' => '7','key_name' => 'mobistar','carrier_name' => 'Mobistar','sms' => '{number}@mobistar.be'),
  array('idPhone_Carriers' => '89','idPhone_Countries' => '8','key_name' => 'claro','carrier_name' => 'Claro','sms' => '{number}@clarotorpedo.com.br'),
  array('idPhone_Carriers' => '90','idPhone_Countries' => '8','key_name' => 'viva_sa','carrier_name' => 'Vivo','sms' => '{number}@torpedoemail.com.br'),
  array('idPhone_Carriers' => '91','idPhone_Countries' => '9','key_name' => 'globul','carrier_name' => 'Globul','sms' => '{number}@sms.globul.bg'),
  array('idPhone_Carriers' => '92','idPhone_Countries' => '9','key_name' => 'mobiltel','carrier_name' => 'Mobiltel','sms' => '{number}@sms.mtel.net'),
  array('idPhone_Carriers' => '93','idPhone_Countries' => '10','key_name' => 'china_mobile','carrier_name' => 'China Mobile','sms' => '{number}@139.com'),
  array('idPhone_Carriers' => '94','idPhone_Countries' => '11','key_name' => 'comcel','carrier_name' => 'Comcel','sms' => '{number}@comcel.com.co'),
  array('idPhone_Carriers' => '95','idPhone_Countries' => '11','key_name' => 'movistar','carrier_name' => 'Movistar','sms' => '{number}@movistar.com.co'),
  array('idPhone_Carriers' => '96','idPhone_Countries' => '12','key_name' => 'vodaphone','carrier_name' => 'Vodaphone','sms' => '{number}@vodafonemail.cz'),
  array('idPhone_Carriers' => '97','idPhone_Countries' => '13','key_name' => 'digicel','carrier_name' => 'Digicel','sms' => '{number}@digitextdm.com'),
  array('idPhone_Carriers' => '98','idPhone_Countries' => '14','key_name' => 'mobinil','carrier_name' => 'Mobinil','sms' => '{number}@mobinil.net'),
  array('idPhone_Carriers' => '99','idPhone_Countries' => '14','key_name' => 'vodaphone','carrier_name' => 'Vodaphone','sms' => '{number}@vodafone.com.eg'),
  array('idPhone_Carriers' => '100','idPhone_Countries' => '15','key_name' => 'foroya_tele','carrier_name' => 'Foroya tele','sms' => '{number}@gsm.fo'),
  array('idPhone_Carriers' => '101','idPhone_Countries' => '16','key_name' => 'sfr','carrier_name' => 'SFR','sms' => '{number}@sfr.fr'),
  array('idPhone_Carriers' => '102','idPhone_Countries' => '16','key_name' => 'bouygues','carrier_name' => 'Bouygues Telecom','sms' => '{number}@mms.bouyguestelecom.fr'),
  array('idPhone_Carriers' => '103','idPhone_Countries' => '17','key_name' => 'eplus','carrier_name' => 'E-Plus','sms' => '{number}@smsmail.eplus.de'),
  array('idPhone_Carriers' => '104','idPhone_Countries' => '17','key_name' => 'o2','carrier_name' => 'O2','sms' => '{number}@o2online.de'),
  array('idPhone_Carriers' => '105','idPhone_Countries' => '17','key_name' => 'vodaphone','carrier_name' => 'Vodaphone','sms' => '{number}@vodafone-sms.de'),
  array('idPhone_Carriers' => '106','idPhone_Countries' => '18','key_name' => 'guyana_telephone','carrier_name' => 'Guyana Telephone & Telegraph','sms' => '{number}@sms.cellinkgy.com'),
  array('idPhone_Carriers' => '107','idPhone_Countries' => '19','key_name' => 'csl','carrier_name' => 'CSL','sms' => '{number}@mgw.mmsc1.hkcsl.com'),
  array('idPhone_Carriers' => '108','idPhone_Countries' => '20','key_name' => 'ogvodafone','carrier_name' => 'OgVodafone','sms' => '{number}@sms.is'),
  array('idPhone_Carriers' => '109','idPhone_Countries' => '20','key_name' => 'siminn','carrier_name' => 'Siminn','sms' => '{number}@box.is'),
  array('idPhone_Carriers' => '110','idPhone_Countries' => '21','key_name' => 'aircel','carrier_name' => 'Aircel','sms' => '{number}@aircel.co.in'),
  array('idPhone_Carriers' => '111','idPhone_Countries' => '21','key_name' => 'aircel_tamil_nadu','carrier_name' => 'Aircel - Tamil Nadu','sms' => '{number}@airsms.com'),
  array('idPhone_Carriers' => '112','idPhone_Countries' => '21','key_name' => 'airtel','carrier_name' => 'Airtel','sms' => '{number}@airtelmail.com'),
  array('idPhone_Carriers' => '113','idPhone_Countries' => '21','key_name' => 'airtel_andhra_pradesh','carrier_name' => 'Airtel - Andhra Pradesh','sms' => '{number}@airtelap.com'),
  array('idPhone_Carriers' => '114','idPhone_Countries' => '21','key_name' => 'airtel_chennai','carrier_name' => 'Airtel - Chennai','sms' => '{number}@airtelchennai.com'),
  array('idPhone_Carriers' => '115','idPhone_Countries' => '21','key_name' => 'airtel_karnataka','carrier_name' => 'Airtel - Karnataka','sms' => '{number}@airtelkk.com'),
  array('idPhone_Carriers' => '116','idPhone_Countries' => '21','key_name' => 'airtel_kerala','carrier_name' => 'Airtel - Kerala','sms' => '{number}@airtelkerala.com'),
  array('idPhone_Carriers' => '117','idPhone_Countries' => '21','key_name' => 'airtel_kolkata','carrier_name' => 'Airtel - Kolkata','sms' => '{number}@airtelkol.com'),
  array('idPhone_Carriers' => '118','idPhone_Countries' => '21','key_name' => 'airtel_tamil_nadu','carrier_name' => 'Airtel - Tamil Nadu','sms' => '{number}@airtelmobile.com'),
  array('idPhone_Carriers' => '119','idPhone_Countries' => '21','key_name' => 'celforce','carrier_name' => 'Celforce','sms' => '{number}@celforce.com'),
  array('idPhone_Carriers' => '120','idPhone_Countries' => '21','key_name' => 'escotel','carrier_name' => 'Escotel Mobile','sms' => '{number}@escotelmobile.com'),
  array('idPhone_Carriers' => '121','idPhone_Countries' => '21','key_name' => 'idea_cellular','carrier_name' => 'Idea Cellular','sms' => '{number}@ideacellular.net'),
  array('idPhone_Carriers' => '122','idPhone_Countries' => '21','key_name' => 'loop','carrier_name' => 'Loop (BPL Mobile)','sms' => '{number}@loopmobile.co.in'),
  array('idPhone_Carriers' => '123','idPhone_Countries' => '21','key_name' => 'orange','carrier_name' => 'Orange','sms' => '{number}@orangemail.co.in'),
  array('idPhone_Carriers' => '124','idPhone_Countries' => '22','key_name' => 'meteor','carrier_name' => 'Meteor','sms' => '{number}@sms.mymeteor.ie'),
  array('idPhone_Carriers' => '125','idPhone_Countries' => '23','key_name' => 'spikko','carrier_name' => 'Spikko','sms' => '{number}@spikkosms.com'),
  array('idPhone_Carriers' => '126','idPhone_Countries' => '24','key_name' => 'vodaphone','carrier_name' => 'Vodaphone','sms' => '{number}@sms.vodafone.it'),
  array('idPhone_Carriers' => '127','idPhone_Countries' => '25','key_name' => 'au','carrier_name' => 'AU by KDDI','sms' => '{number}@ezweb.ne.jp'),
  array('idPhone_Carriers' => '128','idPhone_Countries' => '25','key_name' => 'ntt','carrier_name' => 'NTT DoCoMo','sms' => '{number}@docomo.ne.jp'),
  array('idPhone_Carriers' => '129','idPhone_Countries' => '25','key_name' => 'vodaphone_chuugoku','carrier_name' => 'Vodaphone - Chuugoku/Western','sms' => '{number}@n.vodafone.ne.jp'),
  array('idPhone_Carriers' => '130','idPhone_Countries' => '25','key_name' => 'vodaphone_hokkaido','carrier_name' => 'Vodaphone - Hokkaido','sms' => '{number}@d.vodafone.ne.jp'),
  array('idPhone_Carriers' => '131','idPhone_Countries' => '25','key_name' => 'vodaphone_hokuriku','carrier_name' => 'Vodaphone - Hokuriku/Central North','sms' => '{number}@r.vodafone.ne.jp'),
  array('idPhone_Carriers' => '132','idPhone_Countries' => '25','key_name' => 'vodaphone_kansai','carrier_name' => 'Vodaphone - Kansai/West','sms' => '{number}@k.vodafone.ne.jp'),
  array('idPhone_Carriers' => '133','idPhone_Countries' => '25','key_name' => 'vodaphone_kanto','carrier_name' => 'Vodaphone - Kanto','sms' => '{number}@k.vodafone.ne.jp'),
  array('idPhone_Carriers' => '134','idPhone_Countries' => '25','key_name' => 'vodaphone_koushin','carrier_name' => 'Vodaphone - Koushin','sms' => '{number}@k.vodafone.ne.jp'),
  array('idPhone_Carriers' => '135','idPhone_Countries' => '25','key_name' => 'vodaphone_kyuushu','carrier_name' => 'Vodaphone - Kyuushu','sms' => '{number}@q.vodafone.ne.jp'),
  array('idPhone_Carriers' => '136','idPhone_Countries' => '25','key_name' => 'vodaphone_niigata','carrier_name' => 'Vodaphone - Niigata/North','sms' => '{number}@h.vodafone.ne.jp'),
  array('idPhone_Carriers' => '137','idPhone_Countries' => '25','key_name' => 'vodaphone_okinawa','carrier_name' => 'Vodaphone - Okinawa','sms' => '{number}@q.vodafone.ne.jp'),
  array('idPhone_Carriers' => '138','idPhone_Countries' => '25','key_name' => 'vodaphone_osaka','carrier_name' => 'Vodaphone - Osaka','sms' => '{number}@k.vodafone.ne.jp'),
  array('idPhone_Carriers' => '139','idPhone_Countries' => '25','key_name' => 'vodaphone_shikoku','carrier_name' => 'Vodaphone - Shikoku','sms' => '{number}@s.vodafone.ne.jp'),
  array('idPhone_Carriers' => '140','idPhone_Countries' => '25','key_name' => 'vodaphone_tokyo','carrier_name' => 'Vodaphone - Tokyo','sms' => '{number}@k.vodafone.ne.jp'),
  array('idPhone_Carriers' => '141','idPhone_Countries' => '25','key_name' => 'vodaphone_touhoku','carrier_name' => 'Vodaphone - Touhoku','sms' => '{number}@h.vodafone.ne.jp'),
  array('idPhone_Carriers' => '142','idPhone_Countries' => '25','key_name' => 'vodaphone_toukai','carrier_name' => 'Vodaphone - Toukai','sms' => '{number}@h.vodafone.ne.jp'),
  array('idPhone_Carriers' => '143','idPhone_Countries' => '25','key_name' => 'willcom','carrier_name' => 'Willcom','sms' => '{number}@pdx.ne.jp'),
  array('idPhone_Carriers' => '144','idPhone_Countries' => '26','key_name' => 'emtel','carrier_name' => 'Emtel','sms' => '{number}@emtelworld.net'),
  array('idPhone_Carriers' => '145','idPhone_Countries' => '27','key_name' => 'nextel','carrier_name' => 'Nextel','sms' => '{number}@msgnextel.com.mx'),
  array('idPhone_Carriers' => '146','idPhone_Countries' => '28','key_name' => 'ncell','carrier_name' => 'Ncell','sms' => '{number}@sms.ncell.com.np'),
  array('idPhone_Carriers' => '147','idPhone_Countries' => '29','key_name' => 'orange','carrier_name' => 'Orange','sms' => '{number}@sms.orange.nl'),
  array('idPhone_Carriers' => '148','idPhone_Countries' => '29','key_name' => 't_mobile','carrier_name' => 'T-Mobile','sms' => '{number}@gin.nl'),
  array('idPhone_Carriers' => '149','idPhone_Countries' => '30','key_name' => 'telecom','carrier_name' => 'Telecom','sms' => '{number}@etxt.co.nz'),
  array('idPhone_Carriers' => '150','idPhone_Countries' => '30','key_name' => 'vodafone','carrier_name' => 'Vodafone','sms' => '{number}@mtxt.co.nz'),
  array('idPhone_Carriers' => '151','idPhone_Countries' => '31','key_name' => 'mas_movil','carrier_name' => 'Mas Movil','sms' => '{number}@cwmovil.com'),
  array('idPhone_Carriers' => '152','idPhone_Countries' => '32','key_name' => 'orange_polska','carrier_name' => 'Orange Polska','sms' => '{number}@sms.orange.pl'),
  array('idPhone_Carriers' => '153','idPhone_Countries' => '32','key_name' => 'polkomtel','carrier_name' => 'Polkomtel','sms' => '+{number}@text.plusgsm.pl'),
  array('idPhone_Carriers' => '154','idPhone_Countries' => '32','key_name' => 'plus','carrier_name' => 'Plus','sms' => '+{number}@text.plusgsm.pl'),
  array('idPhone_Carriers' => '155','idPhone_Countries' => '33','key_name' => 'claro','carrier_name' => 'Claro','sms' => '{number}@vtexto.com'),
  array('idPhone_Carriers' => '156','idPhone_Countries' => '34','key_name' => 'beeline','carrier_name' => 'Beeline','sms' => '{number}@sms.beemail.ru'),
  array('idPhone_Carriers' => '157','idPhone_Countries' => '35','key_name' => 'm1','carrier_name' => 'M1','sms' => '{number}@m1.com.sg'),
  array('idPhone_Carriers' => '158','idPhone_Countries' => '36','key_name' => 'mtn','carrier_name' => 'MTN','sms' => '{number}@sms.co.za'),
  array('idPhone_Carriers' => '159','idPhone_Countries' => '36','key_name' => 'vodacom','carrier_name' => 'Vodacom','sms' => '{number}@voda.co.za'),
  array('idPhone_Carriers' => '160','idPhone_Countries' => '37','key_name' => 'helio','carrier_name' => 'Helio','sms' => '{number}@myhelio.com'),
  array('idPhone_Carriers' => '161','idPhone_Countries' => '38','key_name' => 'esendex','carrier_name' => 'Esendex','sms' => '{number}@esendex.net'),
  array('idPhone_Carriers' => '162','idPhone_Countries' => '38','key_name' => 'movistar','carrier_name' => 'Movistar/Telefonica','sms' => '{number}@movistar.net'),
  array('idPhone_Carriers' => '163','idPhone_Countries' => '38','key_name' => 'movistar','carrier_name' => 'Movistar/Telefonica','sms' => '{number}@correo.movistar.net'),
  array('idPhone_Carriers' => '164','idPhone_Countries' => '38','key_name' => 'vodaphone','carrier_name' => 'Vodaphone','sms' => '{number}@vodafone.es'),
  array('idPhone_Carriers' => '165','idPhone_Countries' => '39','key_name' => 'mobitel','carrier_name' => 'Mobitel','sms' => '{number}@sms.mobitel.lk'),
  array('idPhone_Carriers' => '166','idPhone_Countries' => '40','key_name' => 'tele2','carrier_name' => 'Tele2','sms' => '{number}@sms.tele2.se'),
  array('idPhone_Carriers' => '167','idPhone_Countries' => '41','key_name' => 'sunrise','carrier_name' => 'Sunrise Communications','sms' => '{number}@gsm.sunrise.ch'),
  array('idPhone_Carriers' => '168','idPhone_Countries' => '42','key_name' => 'Beeline','carrier_name' => 'Beeline','sms' => '{number}@sms.beeline.ua'),
  array('idPhone_Carriers' => '169','idPhone_Countries' => '43','key_name' => 'aql','carrier_name' => 'aql','sms' => '{number}@text.aql.com'),
  array('idPhone_Carriers' => '170','idPhone_Countries' => '43','key_name' => 'esendex','carrier_name' => 'Esendex','sms' => '{number}@echoemail.net'),
  array('idPhone_Carriers' => '171','idPhone_Countries' => '43','key_name' => 'hay_systems','carrier_name' => 'HSL Mobile (Hay Systems Ltd)','sms' => '{number}@sms.haysystems.com'),
  array('idPhone_Carriers' => '172','idPhone_Countries' => '43','key_name' => 'o2','carrier_name' => 'O2','sms' => '{number}@mmail.co.uk'),
  array('idPhone_Carriers' => '173','idPhone_Countries' => '43','key_name' => 'orange','carrier_name' => 'Orange','sms' => '{number}@orange.net'),
  array('idPhone_Carriers' => '174','idPhone_Countries' => '43','key_name' => 't_mobile','carrier_name' => 'T-Mobile','sms' => '{number}@t-mobile.uk.net'),
  array('idPhone_Carriers' => '175','idPhone_Countries' => '43','key_name' => 'txtlocal','carrier_name' => 'Txtlocal','sms' => '{number}@txtlocal.co.uk'),
  array('idPhone_Carriers' => '176','idPhone_Countries' => '43','key_name' => 'unimovil','carrier_name' => 'UniMovil Corporation','sms' => '{number}@viawebsms.com'),
  array('idPhone_Carriers' => '177','idPhone_Countries' => '44','key_name' => 'movistar','carrier_name' => 'Movistar','sms' => '{number}@sms.movistar.com.uy'),
  array('idPhone_Carriers' => '178','idPhone_Countries' => '45','key_name' => 'tellustalk','carrier_name' => 'TellusTalk','sms' => '{number}@esms.nu'),
  array('idPhone_Carriers' => '179','idPhone_Countries' => '46','key_name' => 'movistar','carrier_name' => 'Movistar','sms' => '{number}@movimensaje.com.ar'),
  array('idPhone_Carriers' => '180','idPhone_Countries' => '47','key_name' => 'globalstar','carrier_name' => 'Globalstar satellite','sms' => '{number}@msg.globalstarusa.com'),
  array('idPhone_Carriers' => '181','idPhone_Countries' => '47','key_name' => 'iridium','carrier_name' => 'Iridium satellite','sms' => '{number}@msg.iridium.com')
);

// `socialjesusfreaks`.`Phone_Countries`
$Phone_Countries = array(
  array('idPhone_Countries' => '2','code' => 'us','name' => 'United States'),
  array('idPhone_Countries' => '3','code' => 'ca','name' => 'Canada'),
  array('idPhone_Countries' => '4','code' => 'ar','name' => 'Argentina'),
  array('idPhone_Countries' => '5','code' => 'aw','name' => 'Aruba'),
  array('idPhone_Countries' => '6','code' => 'au','name' => 'Australia'),
  array('idPhone_Countries' => '7','code' => 'be','name' => 'Belgium'),
  array('idPhone_Countries' => '8','code' => 'br','name' => 'Brazil'),
  array('idPhone_Countries' => '9','code' => 'bg','name' => 'Bulgaria'),
  array('idPhone_Countries' => '10','code' => 'cn','name' => 'China'),
  array('idPhone_Countries' => '11','code' => 'co','name' => 'Columbia'),
  array('idPhone_Countries' => '12','code' => 'cz','name' => 'Czech Republic'),
  array('idPhone_Countries' => '13','code' => 'dm','name' => 'Dominica'),
  array('idPhone_Countries' => '14','code' => 'eg','name' => 'Egypt'),
  array('idPhone_Countries' => '15','code' => 'fo','name' => 'Faroe Islands'),
  array('idPhone_Countries' => '16','code' => 'fr','name' => 'France'),
  array('idPhone_Countries' => '17','code' => 'de','name' => 'Germany'),
  array('idPhone_Countries' => '18','code' => 'gy','name' => 'Guyana'),
  array('idPhone_Countries' => '19','code' => 'hk','name' => 'Hong Kong'),
  array('idPhone_Countries' => '20','code' => 'is','name' => 'Iceland'),
  array('idPhone_Countries' => '21','code' => 'in','name' => 'India'),
  array('idPhone_Countries' => '22','code' => 'ie','name' => 'Ireland'),
  array('idPhone_Countries' => '23','code' => 'il','name' => 'Israel'),
  array('idPhone_Countries' => '24','code' => 'it','name' => 'Italy'),
  array('idPhone_Countries' => '25','code' => 'jp','name' => 'Japan'),
  array('idPhone_Countries' => '26','code' => 'mu','name' => 'Mauritius'),
  array('idPhone_Countries' => '27','code' => 'mx','name' => 'Mexico'),
  array('idPhone_Countries' => '28','code' => 'np','name' => 'Nepal'),
  array('idPhone_Countries' => '29','code' => 'nl','name' => 'Netherlands'),
  array('idPhone_Countries' => '30','code' => 'nz','name' => 'New Zealand'),
  array('idPhone_Countries' => '31','code' => 'pa','name' => 'Panama'),
  array('idPhone_Countries' => '32','code' => 'pl','name' => 'Poland'),
  array('idPhone_Countries' => '33','code' => 'pr','name' => 'Puerto Rico'),
  array('idPhone_Countries' => '34','code' => 'ru','name' => 'Russia'),
  array('idPhone_Countries' => '35','code' => 'sg','name' => 'Singapore'),
  array('idPhone_Countries' => '36','code' => 'za','name' => 'South Africa'),
  array('idPhone_Countries' => '37','code' => 'kr','name' => 'South Korea'),
  array('idPhone_Countries' => '38','code' => 'es','name' => 'Spain'),
  array('idPhone_Countries' => '39','code' => 'lk','name' => 'Sri Lanka'),
  array('idPhone_Countries' => '40','code' => 'se','name' => 'Sweden'),
  array('idPhone_Countries' => '41','code' => 'ch','name' => 'Switzerland'),
  array('idPhone_Countries' => '42','code' => 'ua','name' => 'Ukraine'),
  array('idPhone_Countries' => '43','code' => 'uk','name' => 'United Kingdom'),
  array('idPhone_Countries' => '44','code' => 'uy','name' => 'Uruguay'),
  array('idPhone_Countries' => '45','code' => 'europe','name' => 'Europe'),
  array('idPhone_Countries' => '46','code' => 'latin_america','name' => 'Latin America'),
  array('idPhone_Countries' => '47','code' => 'int','name' => 'International')
);
